import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Search from "@/components/Search";
import Weather from "@/components/Weather";
import { example } from "@/utils/example";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Weather app</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/rain.svg" />
			</Head>
			<Layout>
				<Search />

				<div className={styles.center}>
					<div>
						<h3>Example result:</h3>
						<Weather
							state={{ fail: false, error: "" }}
							city={example}></Weather>
					</div>
				</div>
			</Layout>
		</>
	);
}
