import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Search from "@/components/Search";
import Weather from "@/components/Weather";
import { example } from "@/utils/example";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Weather app</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/rain.svg" />
			</Head>

			<Search />

			<div className={styles.center}>
				<div>
					<h3>Example result:</h3>
					<Weather state={{ fail: false, error: "" }} city={example}></Weather>
				</div>

				{/* <a
						href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
						target="_blank"
						rel="noopener noreferrer">
						<h2 className={inter.className}>
							example <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Find in-depth information about Next.js features and&nbsp;API.
						</p>
					</a> */}
			</div>
		</>
	);
}
